package com.devnear.web.domain.enums;

public enum NotificationType {
    PROJECT_PROPOSAL_SENT,
    PROJECT_PROPOSAL_ACCEPTED,
    PROJECT_PROPOSAL_REJECTED,
    PROJECT_APPLICATION_SUBMITTED,
    PROJECT_APPLICATION_ACCEPTED,
    PROJECT_APPLICATION_REJECTED,
    CHAT_ROOM_CREATED,
    PROJECT_COMPLETED_REVIEW_REQUEST,
    PAYMENT_COMPLETED,
    FREELANCER_DEPOSIT_COMPLETED,
    REVIEW_LEFT_BY_CLIENT,
    REVIEW_LEFT_BY_FREELANCER,
    COMMUNITY_COMMENT_ON_MY_POST,
    PROJECT_DEADLINE_CLOSED
}
