package com.devnear.web.domain.enums;

public enum NotificationType {
    PROJECT_PROPOSAL_SENT,
    PROJECT_PROPOSAL_ACCEPTED,
    PROJECT_PROPOSAL_REJECTED,
    PROJECT_APPLICATION_SUBMITTED,
    PROJECT_APPLICATION_ACCEPTED,
    PROJECT_APPLICATION_REJECTED,
    CHAT_ROOM_CREATED
}
